<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="4031" started-at="2019-12-09T09:39:14Z" finished-at="2019-12-09T09:39:18Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="4031" started-at="2019-12-09T09:39:14Z" finished-at="2019-12-09T09:39:18Z">
      <class name="com.test.git.testNG.TimeOutTest">
        <test-method status="FAIL" signature="testFailed()[pri:0, instance:com.test.git.testNG.TimeOutTest@7ac7a4e4]" name="testFailed" duration-ms="2013" started-at="2019-12-09T17:39:14Z" finished-at="2019-12-09T17:39:16Z">
          <exception class="org.testng.internal.thread.ThreadTimeoutException">
            <message>
              <![CDATA[Method org.testng.internal.TestNGMethod.testFailed() didn't finish within the time-out 2000]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method org.testng.internal.TestNGMethod.testFailed() didn't finish within the time-out 2000
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.internal.thread.ThreadTimeoutException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testFailed -->
        <test-method status="PASS" signature="testSuccess()[pri:0, instance:com.test.git.testNG.TimeOutTest@7ac7a4e4]" name="testSuccess" duration-ms="2001" started-at="2019-12-09T17:39:16Z" finished-at="2019-12-09T17:39:18Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testSuccess -->
      </class> <!-- com.test.git.testNG.TimeOutTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
